name: HPN-SSH-cloudflared

on:
  workflow_dispatch:
      
jobs:
  launch_ssh:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: extract
        run: |
          tar -xf rclone.zip
          tar -xf stunserver_win64_1_2_16.zip
          7z e nmap-7.80-setup.zip
          7z e cloudflared.7z
          7z x HPN-SSH.7z -oHPN-SSH
      
      - name: install 
        run: |
          Start-Process -Wait -FilePath msiexec -ArgumentList /i, "winfsp.msi", /qn
          Start-Process -Wait -FilePath msiexec -ArgumentList /i, "wireguard-amd64-0.5.3.msi", /qn
          Start-Process -Wait -FilePath ./nmap-7.80-setup.exe -ArgumentList /S
          
      - name: run ssh server
        run: |
          $cygroot="$PWD\HPN-SSH"
          $cyghome="${root}\home\${env:UserName}"
          $ENV:PATH="$root\bin;$root\usr\local\bin;$ENV:PATH"
          $Key = "$cygroot\usr\local\etc\hpnssh\ssh_host_rsa_key"
          
          md $cyghome\.ssh
          
          "${{secrets.PUB_KEY}}" | Out-File $cyghome\.ssh\authorized_keys
          "${{secrets.PRVT_KEY}}" | Out-File $cyghome\.ssh\id_rsa
          "${{secrets.HOST_PRVT_KEY}}" | Out-File $Key
          
          Icacls $Key /c /t /Inheritance:d
          Icacls $Key /c /t /Grant ${env:UserName}:F
          TakeOwn /F $Key
          Icacls $Key /c /t /Grant:r ${env:UserName}:F
          Icacls $Key /c /t /Remove:g SYSTEM Users Administrators
          Icacls $Key
          
          New-NetFirewallRule -DisplayName “Allow HPN-SSH” -Direction Inbound -LocalPort 2222 -Protocol TCP -Action Allow
          & $cygroot\usr\local\bin\hpnsshd.exe
          
      - name: clean
        run: |
          del stunserver_win64_1_2_16.zip 
          del rclone.zip 
          del OpenSSH-Win64.zip
          del wireguard-amd64-0.5.3.msi
          del winfsp.msi
          del cloudflared.7z
          del HPN-SSH.7z
          del nmap-7.80-setup.exe
          del nmap-7.80-setup.zip
          del nmap-7.80-setup.z05
          del nmap-7.80-setup.z04
          del nmap-7.80-setup.z03
          del nmap-7.80-setup.z02
          del nmap-7.80-setup.z01
          
      - name: cloudflared
        run: |
          $pinfo = New-Object System.Diagnostics.ProcessStartInfo
          $pinfo.FileName = "cloudflared.exe"
          $pinfo.RedirectStandardError = $true
          $pinfo.RedirectStandardOutput = $true
          $pinfo.UseShellExecute = $false
          $pinfo.Arguments = "tunnel --no-autoupdate --url tcp://localhost:2222"
          $p = New-Object System.Diagnostics.Process
          $p.StartInfo = $pinfo
          $p.Start() | Out-Null
          while ($true) {
              $line = $p.StandardError.ReadLine()
              if ($line.Contains(".trycloudflare.com")){
                  break
              }
          }

          $link = $line.Split(" ", [System.StringSplitOptions]::RemoveEmptyEntries)[3]
          echo $link
          $uri = "https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage"
          $Parameters = @{
              chat_id = ${{secrets.CHAT_ID}}
              text = $link
          }
          Invoke-WebRequest -Uri $uri -Body $Parameters -Method Get
          sleep 10000
          
      
