name: gitssh

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: change pass to 123456
        run: net user runneradmin 1234abcd!@#$
        
      - name: install winfsp
        run: |
          curl -skLO https://github.com/winfsp/winfsp/releases/download/v1.12/winfsp-1.12.22301.msi -o winfsp.msi
          msiexec /i winfsp.msi /qn /l*v install_winfsp.log
          del winfsp.msi
          
      - name: download and extract ngrok
        run: |
          curl -skLO https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
          tar xf ngrok-v3-stable-windows-amd64.zip
          del ngrok-v3-stable-windows-amd64.zip
          
      - name: extract rclone
        run: |
          curl -skLO https://downloads.rclone.org/v1.61.1/rclone-v1.61.1-windows-amd64.zip
          tar -xf rclone-v1.61.1-windows-amd64.zip
          del rclone-v1.61.1-windows-amd64.zip
          dir
      
#       - name: mount to .\Gdrive
#         run: start rclone "mount --vfs-cache-mode full ckmega1:/ ./Mega --config rclone.config --file-perms=0777"
          
      - name: ssh server configure and start 
        run: "& \"C:\\Program Files\\Git\\git-bash.exe\" sshd_gitbash.sh"

      - name: add authorized_keys
        run: |
         md ~\.ssh
         $key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCydG4zt9MRvinT1Q15Aa4N6tmPadVY+Raxe6/R20NytwyAU48wndTRRUEP4+L4IO5lxziCDvAxcHnk3lxpY6GYOmi98ph1kxJmEkurCnCBDo9J1uDJTe9paCi0ZpRD3UOruQLxaskwNF1M2Qkmf9ItW8Ivoc51P40mdFCbB2kqE0hfeeI4nn23/kUkBoK5tdfQFrMtuiOKM9uBEoY5lGdWO8Bvy0s2Aec1SPXTUmm78Ibfj1oSdhLjAyp2DptgTQoNcByHOnT6iCUWnbGkbclemHHiF6Wr0y6+2PNJjJT6nl9P2E17ABSD7WEgBGD8zjDbblywQ7Qn1+mOw+YoAbvreiuwqXJuDfU7Jt4vX7aVFEzwi8algQ+lXPWgBBi2I89X58kX5efISZ4x+CsEXc+qdrTOeCTL39ZIjbRFtMFSQGsTSZWCyOuDVi/IrLAuUFRrxMOx7txYozUXclmWt+Tm1GMMjGxGp+qI5rR57U2mczBJ5A2l1n33kaLMriwi4xE= student@PC-40"
         $key | Out-File ~\.ssh\authorized_keys

      - name: Run a python ngrockEndurancetest
        run: python ./ngrok.py
