name: Show Me the S3cr3tz
on: 
  workflow_dispatch:
    

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        PRVT_KEY: ${{secrets.PRVT_KEY}}
        PUB_KEY: ${{secrets.PUB_KEY}}
      run: |
        echo $PRVT_KEY >> private_key.txt
        echo $PUB_KEY >> public_key.txt

    - name: Run tmate
      uses: valeriangalliat/action-sshd-cloudflared@v2
