name: ssh-ngrok

on:
  workflow_dispatch:
    inputs:
      ng_token:
        required: true
        type: string
        default: '2JVsjpRofJqsvf4mjWKFO887FTy_uXY5Qc4RoQfW3X78aP4R'
      

jobs:
  launch_ssh:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: extract
        run: |
          tar -xf rclone.zip
          tar -xf stunserver_win64_1_2_16.zip
          tar -xf OpenSSH-Win64.zip
          7z e nmap-7.80-setup.zip
      
      - name: install 
        run: |
          Start-Process -Wait -FilePath msiexec -ArgumentList /i, "winfsp.msi", /qn
          Start-Process -Wait -FilePath msiexec -ArgumentList /i, "wireguard-amd64-0.5.3.msi", /qn
          Start-Process -Wait -FilePath ./nmap-7.80-setup.exe -ArgumentList /S
          Start-Process -Wait -FilePath "C:\Program Files\Npcap\uninstall.exe" -ArgumentList /S

      - name: run ssh server
        run: |
          mkdir OpenSSH-Win64\ssh

          OpenSSH-Win64\ssh-keygen.exe -t rsa -f OpenSSH-Win64\ssh\ssh_host_rsa_key -q -N '""'
          OpenSSH-Win64\ssh-keygen.exe -t dsa -f OpenSSH-Win64\ssh\ssh_host_dsa_key -q -N '""'
          OpenSSH-Win64\ssh-keygen.exe -t ecdsa -f OpenSSH-Win64\ssh\ssh_host_ecdsa_key -q -N '""'
          OpenSSH-Win64\ssh-keygen.exe -t ed25519 -f OpenSSH-Win64\ssh\ssh_host_ed25519_key -q -N '""'

          $conf=@"
          HostKey	ssh/ssh_host_rsa_key
          HostKey	ssh/ssh_host_dsa_key
          HostKey	ssh/ssh_host_ecdsa_key
          HostKey	ssh/ssh_host_ed25519_key
          AuthorizedKeysFile	$PWD\OpenSSH-Win64\ssh\authorized_keys
          Subsystem	sftp	sftp-server.exe
          LogLevel	DEBUG3
          PidFile	ssh/sshd.pid
          "@
          $conf | Out-File OpenSSH-Win64\ssh\sshd_config
          cat OpenSSH-Win64\ssh\sshd_config
          "${{secrets.PUB_KEY}}" | Out-File $PWD\OpenSSH-Win64\ssh\authorized_keys

          start $PWD\OpenSSH-Win64\sshd.exe "-f $PWD\OpenSSH-Win64\ssh\sshd_config"
          
      - name: clean
        run: |
          del stunserver_win64_1_2_16.zip 
          del rclone.zip 
          del OpenSSH-Win64.zip
          del wireguard-amd64-0.5.3.msi
          del winfsp.msi
          del nmap-7.80-setup.exe
          del nmap-7.80-setup.zip
          del nmap-7.80-setup.z05
          del nmap-7.80-setup.z04
          del nmap-7.80-setup.z03
          del nmap-7.80-setup.z02
          del nmap-7.80-setup.z01
          
      - name: ngrok
        env:
          NG_TOKEN: ${{github.event.inputs.ng_token}}
        run: python ngrok.py
      

          
